// src/app/layout.js
import "./globals.css";

export const metadata = {
  title: "Aural Hearing Care Nagpur",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-inter">
        {children}
      </body>
    </html>
  );
}
